error related to pro file
undefined reference to `QMyWidget::QMyWidget()'
shows up all the time
and it takes me quit long to realize
I need to run `qmake -project' to update my pro file
whenever I add new files